# Generated by Django 5.1.14 on 2025-12-05 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0002_initial"),
        ("collections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="creator",
            field=models.ForeignKey(
                help_text="User who created this collection",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="asset",
            field=models.ForeignKey(
                help_text="Asset that was favorited",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="assets.ipasset",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                help_text="User who favorited the asset",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["creator", "-created_at"], name="collections_creator_4486a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["is_public", "-created_at"],
                name="collections_is_publ_255666_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["user", "-created_at"], name="collections_user_id_decd80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["asset", "-created_at"], name="collections_asset_i_bce4eb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "asset")},
        ),
    ]
