# Generated by Django 5.1.14 on 2025-12-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loreuser",
            index=models.Index(
                fields=["wallet_address"], name="core_loreus_wallet__cee11a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loreuser",
            index=models.Index(
                fields=["-created_at"], name="core_loreus_created_5020f0_idx"
            ),
        ),
    ]
