# Generated by Django 5.1.14 on 2025-12-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="loreuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="loreuser",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email address (optional)",
                max_length=254,
                null=True,
            ),
        ),
    ]
