# Generated by Django 5.1.14 on 2025-12-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_loreuser_core_loreus_wallet__cee11a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loreuser",
            name="banner_url",
            field=models.URLField(
                blank=True, help_text="Profile banner/cover image URL"
            ),
        ),
    ]
