# Generated by Django 5.1.14 on 2025-12-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "story_ip_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Story Protocol IP Asset ID (on-chain)",
                        max_length=66,
                        null=True,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Asset title", max_length=255)),
                ("description", models.TextField(help_text="Asset description/lore")),
                (
                    "media_url",
                    models.URLField(help_text="URL to media file (Azure Blob Storage)"),
                ),
                (
                    "metadata_hash",
                    models.CharField(
                        blank=True,
                        help_text="IPFS hash of metadata JSON",
                        max_length=66,
                    ),
                ),
                (
                    "is_derivative",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this asset is a derivative/remix",
                    ),
                ),
                (
                    "royalty_percentage",
                    models.IntegerField(
                        default=50,
                        help_text="Royalty percentage for derivatives (0-100)",
                    ),
                ),
                (
                    "allow_derivatives",
                    models.BooleanField(
                        default=True, help_text="Allow others to create derivatives"
                    ),
                ),
                (
                    "commercial_rights",
                    models.BooleanField(
                        default=False, help_text="Allow commercial use"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when asset was deleted",
                        null=True,
                    ),
                ),
                (
                    "registration_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Registration"),
                            ("registered", "Registered"),
                            ("failed", "Registration Failed"),
                            ("retrying", "Retrying Registration"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Status of Story Protocol registration",
                        max_length=20,
                    ),
                ),
                (
                    "registration_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if registration failed",
                        null=True,
                    ),
                ),
                (
                    "registration_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of registration attempts"
                    ),
                ),
                (
                    "last_registration_attempt",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last registration attempt",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IP Asset",
                "verbose_name_plural": "IP Assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoyaltyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Royalty amount in ETH",
                        max_digits=20,
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        help_text="Blockchain transaction hash",
                        max_length=66,
                        unique=True,
                    ),
                ),
                (
                    "block_number",
                    models.IntegerField(
                        help_text="Block number where payment occurred"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Royalty Payment",
                "verbose_name_plural": "Royalty Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
