# Generated by Django 5.1.14 on 2025-12-05 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ipasset",
            name="creator",
            field=models.ForeignKey(
                help_text="User who created this asset",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ipasset",
            name="parent_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent asset if this is a derivative",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derivatives",
                to="assets.ipasset",
            ),
        ),
        migrations.AddField(
            model_name="royaltypayment",
            name="asset",
            field=models.ForeignKey(
                help_text="Asset that generated this royalty",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="royalty_payments",
                to="assets.ipasset",
            ),
        ),
        migrations.AddField(
            model_name="royaltypayment",
            name="recipient",
            field=models.ForeignKey(
                help_text="User receiving the royalty",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="royalty_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["is_deleted", "-created_at"],
                name="assets_ipas_is_dele_e60ab6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["creator", "-created_at"], name="assets_ipas_creator_4491b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["is_derivative", "-created_at"],
                name="assets_ipas_is_deri_4327bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["allow_derivatives", "-created_at"],
                name="assets_ipas_allow_d_080603_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["commercial_rights", "-created_at"],
                name="assets_ipas_commerc_f50b80_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["created_at"], name="assets_ipas_created_e27a9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["story_ip_id"], name="assets_ipas_story_i_6b4653_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["registration_status", "-created_at"],
                name="assets_ipas_registr_f311c3_idx",
            ),
        ),
    ]
