# Generated by Django 5.0.14 on 2025-11-30 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ipasset',
            name='creator',
            field=models.ForeignKey(help_text='User who created this asset', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipasset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, help_text='Parent asset if this is a derivative', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='assets.ipasset'),
        ),
        migrations.AddField(
            model_name='royaltypayment',
            name='asset',
            field=models.ForeignKey(help_text='Asset that generated this royalty', on_delete=django.db.models.deletion.CASCADE, related_name='royalty_payments', to='assets.ipasset'),
        ),
        migrations.AddField(
            model_name='royaltypayment',
            name='recipient',
            field=models.ForeignKey(help_text='User receiving the royalty', on_delete=django.db.models.deletion.CASCADE, related_name='royalty_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
