# Generated by Django 5.1.14 on 2025-12-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_add_creation_step_tracking"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ipasset",
            new_name="assets_ipas_creatio_ef1653_idx",
            old_name="assets_ipas_creatio_123abc_idx",
        ),
        migrations.RenameIndex(
            model_name="ipasset",
            new_name="assets_ipas_failed__23ccd6_idx",
            old_name="assets_ipas_failed__456def_idx",
        ),
    ]
