# Generated by Django 5.1.14 on 2025-12-04 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_aiusagestats_aigenerationlog_aiassetmetadata_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ipasset",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when asset was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="ipasset",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Soft delete flag"
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["is_deleted", "-created_at"],
                name="assets_ipas_is_dele_e60ab6_idx",
            ),
        ),
    ]
