# Generated by Django 5.1.14 on 2025-12-04 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_ipasset_deleted_at_ipasset_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["creator", "-created_at"], name="assets_ipas_creator_4491b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["is_derivative", "-created_at"],
                name="assets_ipas_is_deri_4327bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["allow_derivatives", "-created_at"],
                name="assets_ipas_allow_d_080603_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["commercial_rights", "-created_at"],
                name="assets_ipas_commerc_f50b80_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["created_at"], name="assets_ipas_created_e27a9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["story_ip_id"], name="assets_ipas_story_i_6b4653_idx"
            ),
        ),
    ]
