# Generated by Django 5.1.14 on 2025-12-06 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_idempotency_and_transaction_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivativeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID for API access', unique=True)),
                ('attribution_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Attribution percentage for this parent (0-100). Must sum to 100 across all parents.', max_digits=5)),
                ('license_terms_id', models.CharField(blank=True, help_text='Story Protocol license terms ID used for this relationship', max_length=66, null=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash for this relationship', max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Derivative Relationship',
                'verbose_name_plural': 'Derivative Relationships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID for API access', unique=True)),
                ('story_dispute_id', models.CharField(blank=True, db_index=True, help_text='Story Protocol Dispute ID (on-chain)', max_length=66, null=True, unique=True)),
                ('reason', models.TextField(help_text='Reason for the dispute')),
                ('evidence_ipfs_hash', models.CharField(blank=True, help_text='IPFS hash of initial evidence', max_length=66, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the dispute', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('upheld', 'Upheld - Dispute valid'), ('rejected', 'Rejected - Dispute invalid'), ('settled', 'Settled - Parties agreed')], help_text='Final result of the dispute', max_length=20, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes from the dispute resolution', null=True)),
                ('raise_transaction_hash', models.CharField(blank=True, help_text='Transaction hash when dispute was raised', max_length=66, null=True)),
                ('resolve_transaction_hash', models.CharField(blank=True, help_text='Transaction hash when dispute was resolved', max_length=66, null=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the dispute was resolved', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID for API access', unique=True)),
                ('description', models.TextField(help_text='Description of the evidence')),
                ('evidence_url', models.URLField(blank=True, help_text='URL to evidence file (IPFS or external)', max_length=500, null=True)),
                ('evidence_ipfs_hash', models.CharField(blank=True, help_text='IPFS hash of evidence file', max_length=66, null=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispute Evidence',
                'verbose_name_plural': 'Dispute Evidence',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID for API access', unique=True)),
                ('story_group_id', models.CharField(blank=True, db_index=True, help_text='Story Protocol Group IP ID (on-chain)', max_length=66, null=True, unique=True)),
                ('name', models.CharField(help_text='Group name', max_length=255)),
                ('description', models.TextField(help_text='Group description')),
                ('royalty_pool_address', models.CharField(blank=True, help_text='On-chain address of royalty pool contract', max_length=42, null=True)),
                ('total_royalty_percentage', models.IntegerField(default=10, help_text='Total royalty percentage for the group (0-100)')),
                ('registration_status', models.CharField(choices=[('pending', 'Pending Registration'), ('registered', 'Registered'), ('failed', 'Registration Failed')], db_index=True, default='pending', help_text='Status of Story Protocol registration', max_length=20)),
                ('registration_transaction_hash', models.CharField(blank=True, help_text='Transaction hash of group registration', max_length=66, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the group is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group IP',
                'verbose_name_plural': 'Group IPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupIPMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID for API access', unique=True)),
                ('revenue_share_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of group revenue allocated to this member (0-100)', max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this membership is active')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, help_text='When this member was removed from the group', null=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash for adding member', max_length=66, null=True)),
            ],
            options={
                'verbose_name': 'Group IP Membership',
                'verbose_name_plural': 'Group IP Memberships',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupRoyaltyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID for API access', unique=True)),
                ('amount', models.DecimalField(decimal_places=6, help_text='Amount distributed in ETH or token', max_digits=20)),
                ('transaction_hash', models.CharField(db_index=True, help_text='Blockchain transaction hash', max_length=66, unique=True)),
                ('block_number', models.IntegerField(help_text='Block number where distribution occurred')),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Group Royalty Distribution',
                'verbose_name_plural': 'Group Royalty Distributions',
                'ordering': ['-distributed_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='ipasset',
            new_name='assets_ipas_idempot_d66f60_idx',
            old_name='assets_ipas_idempot_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='ipasset',
            new_name='assets_ipas_transac_d706e1_idx',
            old_name='assets_ipas_transac_def456_idx',
        ),
        migrations.AlterField(
            model_name='ipasset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, help_text='[DEPRECATED] Legacy single parent - use parent_assets instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_derivatives', to='assets.ipasset'),
        ),
        migrations.AddField(
            model_name='derivativerelationship',
            name='child_asset',
            field=models.ForeignKey(help_text='Derivative asset (child)', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='assets.ipasset'),
        ),
        migrations.AddField(
            model_name='derivativerelationship',
            name='parent_asset',
            field=models.ForeignKey(help_text='Parent asset being derived from', on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='assets.ipasset'),
        ),
        migrations.AddField(
            model_name='ipasset',
            name='parent_assets',
            field=models.ManyToManyField(blank=True, help_text='Parent assets for multi-parent derivatives', related_name='derivatives', through='assets.DerivativeRelationship', to='assets.ipasset'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='disputer',
            field=models.ForeignKey(help_text='User who raised the dispute', on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='User/admin who resolved the dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='target_asset',
            field=models.ForeignKey(help_text='IP asset being disputed', on_delete=django.db.models.deletion.CASCADE, related_name='disputes_against', to='assets.ipasset'),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='dispute',
            field=models.ForeignKey(help_text='Dispute this evidence is for', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='assets.dispute'),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='submitted_by',
            field=models.ForeignKey(help_text='User who submitted this evidence', on_delete=django.db.models.deletion.CASCADE, related_name='dispute_evidence_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupip',
            name='creator',
            field=models.ForeignKey(help_text='User who created this group', on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupipmembership',
            name='added_by',
            field=models.ForeignKey(help_text='User who added this member to the group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_additions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupipmembership',
            name='asset',
            field=models.ForeignKey(help_text='IP asset that is a member', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='assets.ipasset'),
        ),
        migrations.AddField(
            model_name='groupipmembership',
            name='group',
            field=models.ForeignKey(help_text='Group this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='assets.groupip'),
        ),
        migrations.AddField(
            model_name='grouproyaltydistribution',
            name='group',
            field=models.ForeignKey(help_text='Group from which royalties were distributed', on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='assets.groupip'),
        ),
        migrations.AddField(
            model_name='grouproyaltydistribution',
            name='membership',
            field=models.ForeignKey(help_text='Member receiving the distribution', on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='assets.groupipmembership'),
        ),
        migrations.AddIndex(
            model_name='derivativerelationship',
            index=models.Index(fields=['child_asset', '-created_at'], name='assets_deri_child_a_426154_idx'),
        ),
        migrations.AddIndex(
            model_name='derivativerelationship',
            index=models.Index(fields=['parent_asset', '-created_at'], name='assets_deri_parent__7c7d3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='derivativerelationship',
            unique_together={('child_asset', 'parent_asset')},
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['target_asset', '-raised_at'], name='assets_disp_target__bfc9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['disputer', '-raised_at'], name='assets_disp_dispute_716b36_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', '-raised_at'], name='assets_disp_status_aea8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['result'], name='assets_disp_result_e2d3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['dispute', '-submitted_at'], name='assets_disp_dispute_aea2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['submitted_by', '-submitted_at'], name='assets_disp_submitt_ae3db7_idx'),
        ),
        migrations.AddIndex(
            model_name='groupip',
            index=models.Index(fields=['creator', '-created_at'], name='assets_grou_creator_71ca02_idx'),
        ),
        migrations.AddIndex(
            model_name='groupip',
            index=models.Index(fields=['registration_status', '-created_at'], name='assets_grou_registr_903c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupip',
            index=models.Index(fields=['is_active', '-created_at'], name='assets_grou_is_acti_b101df_idx'),
        ),
        migrations.AddIndex(
            model_name='groupipmembership',
            index=models.Index(fields=['group', 'is_active'], name='assets_grou_group_i_52b160_idx'),
        ),
        migrations.AddIndex(
            model_name='groupipmembership',
            index=models.Index(fields=['asset', 'is_active'], name='assets_grou_asset_i_4d4690_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupipmembership',
            unique_together={('group', 'asset')},
        ),
        migrations.AddIndex(
            model_name='grouproyaltydistribution',
            index=models.Index(fields=['group', '-distributed_at'], name='assets_grou_group_i_5ffa62_idx'),
        ),
        migrations.AddIndex(
            model_name='grouproyaltydistribution',
            index=models.Index(fields=['membership', '-distributed_at'], name='assets_grou_members_617b9d_idx'),
        ),
    ]
