# Generated by Django 5.1.14 on 2025-12-04 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_ipasset_assets_ipas_creator_4491b1_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Collection title", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Collection description"),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True, help_text="URL to collection cover image", null=True
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Whether collection is publicly visible"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="IP assets in this collection",
                        related_name="collections",
                        to="assets.ipasset",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User who created this collection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["creator", "-created_at"],
                        name="assets_coll_creator_cd54ca_idx",
                    ),
                    models.Index(
                        fields=["is_public", "-created_at"],
                        name="assets_coll_is_publ_34aed7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset that was favorited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="assets.ipasset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who favorited the asset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="assets_favo_user_id_9dd343_idx",
                    ),
                    models.Index(
                        fields=["asset", "-created_at"],
                        name="assets_favo_asset_i_7831b5_idx",
                    ),
                ],
                "unique_together": {("user", "asset")},
            },
        ),
    ]
