# Generated by Django 5.1.14 on 2025-12-06 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_add_multi_parent_derivatives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAccountPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('grantee_address', models.CharField(help_text='Wallet address of the grantee (lowercase)', max_length=42)),
                ('permission_type', models.CharField(choices=[('execute', 'Execute Transactions'), ('transfer_erc20', 'Transfer ERC20 Tokens'), ('set_metadata', 'Set Metadata'), ('attach_license', 'Attach License Terms'), ('register_derivative', 'Register Derivatives'), ('collect_royalty', 'Collect Royalties')], help_text='Type of permission granted', max_length=20)),
                ('is_granted', models.BooleanField(default=True, help_text='Whether permission is currently granted (True) or revoked (False)')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this permission expires (null = no expiration)', null=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='Transaction hash from blockchain', max_length=66)),
                ('block_number', models.BigIntegerField(blank=True, help_text='Block number where permission was set', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this permission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='IP asset this permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='assets.ipasset')),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Account Permission',
                'verbose_name_plural': 'IP Account Permissions',
                'db_table': 'assets_ipaccountpermission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset', 'grantee_address'], name='assets_ipac_asset_g_idx'), models.Index(fields=['asset', 'permission_type'], name='assets_ipac_asset_p_idx'), models.Index(fields=['grantee_address', '-created_at'], name='assets_ipac_grantee_idx'), models.Index(fields=['is_granted', '-created_at'], name='assets_ipac_granted_idx'), models.Index(fields=['expires_at'], name='assets_ipac_expires_idx')],
                'unique_together': {('asset', 'grantee_address', 'permission_type')},
            },
        ),
    ]
