# Generated by Django 5.1.15 on 2025-12-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_add_permissions_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouproyaltydistribution',
            name='block_number',
            field=models.BigIntegerField(help_text='Block number where distribution occurred'),
        ),
        migrations.AlterField(
            model_name='ipasset',
            name='media_url',
            field=models.URLField(help_text='URL to media file (IPFS via Pinata)'),
        ),
        migrations.AlterField(
            model_name='royaltypayment',
            name='block_number',
            field=models.BigIntegerField(help_text='Block number where payment occurred'),
        ),
    ]
