# Generated by Django 5.1.15 on 2025-12-09 17:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_grouproyaltydistribution_block_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='derivativerelationship',
            name='fee_paid',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Minting fee paid for this parent relationship in ETH', max_digits=10),
        ),
        migrations.AddField(
            model_name='ipasset',
            name='minting_fee',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.005'), help_text='Minting fee in ETH for derivative creation (set by creator)', max_digits=10),
        ),
        migrations.CreateModel(
            name='MintingFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID for API access', unique=True)),
                ('fee_amount', models.DecimalField(decimal_places=6, help_text='Fee amount in ETH', max_digits=10)),
                ('fee_amount_wei', models.CharField(help_text='Fee amount in Wei (as string for precision)', max_length=78)),
                ('attribution_percentage', models.DecimalField(decimal_places=2, help_text='Attribution percentage for this parent (0-100)', max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Platform fee portion (5% of total)', max_digits=10)),
                ('creator_fee', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Creator fee portion (95% of total)', max_digits=10)),
                ('transaction_hash', models.CharField(blank=True, db_index=True, help_text='Blockchain transaction hash', max_length=66, null=True)),
                ('block_number', models.BigIntegerField(blank=True, help_text='Block number where payment occurred', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('claimed', 'Claimed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the fee was paid', null=True)),
                ('claimed_at', models.DateTimeField(blank=True, help_text='When the fee was claimed by parent creator', null=True)),
                ('derivative_asset', models.ForeignKey(help_text='Derivative asset that was created', on_delete=django.db.models.deletion.PROTECT, related_name='minting_fee_payments', to='assets.ipasset')),
                ('parent_asset', models.ForeignKey(help_text='Parent asset whose creator receives the fee', on_delete=django.db.models.deletion.PROTECT, related_name='minting_fees_received', to='assets.ipasset')),
                ('payer', models.ForeignKey(help_text='User who paid the minting fee', on_delete=django.db.models.deletion.PROTECT, related_name='minting_fees_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Minting Fee Payment',
                'verbose_name_plural': 'Minting Fee Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payer', 'status'], name='assets_mint_payer_i_796670_idx'), models.Index(fields=['parent_asset', 'status'], name='assets_mint_parent__471f62_idx'), models.Index(fields=['derivative_asset'], name='assets_mint_derivat_d1ea73_idx'), models.Index(fields=['status', '-created_at'], name='assets_mint_status_f4b098_idx')],
            },
        ),
    ]
