"""
Constants for IP Assets app.
"""

# Registration Status
REGISTRATION_STATUS_PENDING = 'pending'
REGISTRATION_STATUS_REGISTERED = 'registered'
REGISTRATION_STATUS_FAILED = 'failed'
REGISTRATION_STATUS_RETRYING = 'retrying'

# File Limits
MAX_FILE_SIZE = 50 * 1024 * 1024  # 50MB
DEFAULT_ROYALTY_PERCENTAGE = 50

# Cache Timeouts
ASSET_LIST_CACHE_TIMEOUT = 300
ASSET_DETAIL_CACHE_TIMEOUT = 600

