# Generated by Django 5.1.14 on 2025-12-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIAssetMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("description", "Description"),
                            ("tags", "Tags/Categories"),
                            ("license", "License Terms"),
                        ],
                        help_text="Type of AI-generated content",
                        max_length=20,
                    ),
                ),
                (
                    "original_content",
                    models.TextField(
                        blank=True, help_text="User's original input (if any)"
                    ),
                ),
                (
                    "ai_generated_content",
                    models.TextField(help_text="AI-generated content"),
                ),
                (
                    "model_used",
                    models.CharField(
                        help_text="LLM model that generated this", max_length=100
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=True, help_text="Whether user accepted this suggestion"
                    ),
                ),
                (
                    "modified_by_user",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user edited AI-generated content",
                    ),
                ),
                (
                    "final_content",
                    models.TextField(
                        blank=True,
                        help_text="Final content after user modifications (if any)",
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User rating of AI output (1-5 stars)",
                        null=True,
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(
                        blank=True, help_text="User feedback on AI output quality"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Asset Metadata",
                "verbose_name_plural": "AI Asset Metadata",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("title", "Title Generation"),
                            ("description", "Description Enhancement"),
                            ("analysis", "Content Analysis"),
                            ("license", "License Suggestion"),
                            ("derivative", "Derivative Analysis"),
                        ],
                        db_index=True,
                        help_text="Type of AI operation",
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(help_text="Input parameters passed to AI"),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, help_text="AI-generated output", null=True
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        help_text="LLM model that processed the request", max_length=100
                    ),
                ),
                (
                    "model_tier",
                    models.CharField(
                        default="fast",
                        help_text="Model tier (fast/quality)",
                        max_length=20,
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        blank=True,
                        help_text="Total tokens consumed (if available)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("rate_limited", "Rate Limited"),
                        ],
                        db_index=True,
                        default="success",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "cache_hit",
                    models.BooleanField(
                        default=False, help_text="Whether result was from cache"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "AI Generation Log",
                "verbose_name_plural": "AI Generation Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Date of statistics", unique=True
                    ),
                ),
                ("total_requests", models.IntegerField(default=0)),
                ("title_requests", models.IntegerField(default=0)),
                ("description_requests", models.IntegerField(default=0)),
                ("analysis_requests", models.IntegerField(default=0)),
                ("license_requests", models.IntegerField(default=0)),
                ("derivative_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("rate_limited_requests", models.IntegerField(default=0)),
                ("cache_hits", models.IntegerField(default=0)),
                ("cache_misses", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Estimated API cost in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "avg_response_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Average response time", null=True
                    ),
                ),
                (
                    "unique_users",
                    models.IntegerField(
                        default=0, help_text="Unique users who used AI features"
                    ),
                ),
                (
                    "acceptance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of AI content accepted by users",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Usage Statistics",
                "verbose_name_plural": "AI Usage Statistics",
                "ordering": ["-date"],
            },
        ),
    ]
