# Generated by Django 5.1.14 on 2025-12-05 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiassetmetadata",
            name="asset",
            field=models.ForeignKey(
                help_text="Asset this metadata belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_metadata",
                to="assets.ipasset",
            ),
        ),
    ]
