# Generated by Django 5.1.14 on 2025-12-05 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aigenerationlog",
            name="user",
            field=models.ForeignKey(
                help_text="User who made the request",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiassetmetadata",
            name="generation_log",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to generation log",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_content",
                to="ai.aigenerationlog",
            ),
        ),
        migrations.AddIndex(
            model_name="aigenerationlog",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_aigenera_user_id_b8d5f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aigenerationlog",
            index=models.Index(
                fields=["operation_type", "-created_at"],
                name="ai_aigenera_operati_2742ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aigenerationlog",
            index=models.Index(
                fields=["status", "-created_at"], name="ai_aigenera_status_db3fad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiassetmetadata",
            index=models.Index(
                fields=["asset", "content_type"], name="ai_aiassetm_asset_i_c5df81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiassetmetadata",
            index=models.Index(
                fields=["accepted", "-created_at"],
                name="ai_aiassetm_accepte_e1068e_idx",
            ),
        ),
    ]
