# Generated by Django 5.1.14 on 2025-12-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_initial'),
        ('assets', '0007_add_permissions_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_likely_original', models.BooleanField(default=True, help_text='Whether the asset appears to be original content')),
                ('similarity_score', models.FloatField(default=0.0, help_text='Overall similarity score (0.0-1.0)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', help_text='Copyright risk assessment', max_length=20)),
                ('potential_matches', models.JSONField(default=list, help_text='List of potential matching assets')),
                ('recommendations', models.JSONField(default=list, help_text='Actionable recommendations for the creator')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence in the analysis (0.0-1.0)')),
                ('processing_time', models.FloatField(default=0.0, help_text='Time taken for analysis in seconds')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, help_text='When the analysis was performed')),
                ('asset', models.OneToOneField(help_text='Asset being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='copyright_analysis', to='assets.ipasset')),
            ],
            options={
                'verbose_name': 'Copyright Analysis Result',
                'verbose_name_plural': 'Copyright Analysis Results',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_tiers', models.JSONField(help_text='Three pricing tiers (conservative, balanced, aggressive)')),
                ('market_average', models.FloatField(help_text='Market average royalty percentage')),
                ('similar_assets_count', models.IntegerField(default=0, help_text='Number of similar assets analyzed')),
                ('demand_prediction', models.FloatField(help_text='Predicted demand score (0-100)')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence in the recommendations (0.0-1.0)')),
                ('reasoning', models.TextField(help_text='Explanation of pricing recommendations')),
                ('processing_time', models.FloatField(default=0.0, help_text='Time taken for analysis in seconds')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, help_text='When the analysis was performed')),
                ('asset', models.OneToOneField(help_text='Asset being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_analysis', to='assets.ipasset')),
            ],
            options={
                'verbose_name': 'Pricing Analysis Result',
                'verbose_name_plural': 'Pricing Analysis Results',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(help_text='Overall quality score (0-100)')),
                ('technical_quality', models.JSONField(help_text='Technical quality metrics (resolution, sharpness, etc.)')),
                ('description_quality', models.JSONField(help_text='Description quality metrics (length, clarity, SEO)')),
                ('metadata_completeness', models.FloatField(help_text='Completeness of metadata (0-100)')),
                ('market_appeal', models.FloatField(help_text='Predicted market appeal (0-100)')),
                ('improvement_suggestions', models.JSONField(default=list, help_text='Suggestions for improving quality')),
                ('strengths', models.JSONField(default=list, help_text='Identified strengths of the asset')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence in the analysis (0.0-1.0)')),
                ('processing_time', models.FloatField(default=0.0, help_text='Time taken for analysis in seconds')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, help_text='When the analysis was performed')),
                ('asset', models.OneToOneField(help_text='Asset being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='quality_analysis', to='assets.ipasset')),
            ],
            options={
                'verbose_name': 'Quality Analysis Result',
                'verbose_name_plural': 'Quality Analysis Results',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationWorkflowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Overall workflow status', max_length=20)),
                ('steps_completed', models.JSONField(default=list, help_text='List of completed validation steps')),
                ('overall_verdict', models.CharField(blank=True, choices=[('approved', 'Approved'), ('warning', 'Approved with Warnings'), ('rejected', 'Rejected')], help_text='Final recommendation', max_length=20, null=True)),
                ('agent_results', models.JSONField(default=dict, help_text='Results from each agent')),
                ('warnings', models.JSONField(default=list, help_text='Warnings raised during validation')),
                ('blockers', models.JSONField(default=list, help_text='Issues that should block minting')),
                ('total_processing_time', models.FloatField(default=0.0, help_text='Total time for all agents')),
                ('started_at', models.DateTimeField(blank=True, help_text='When validation started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When validation completed', null=True)),
                ('asset', models.OneToOneField(help_text='Asset being validated', on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='assets.ipasset')),
            ],
            options={
                'verbose_name': 'Validation Workflow Result',
                'verbose_name_plural': 'Validation Workflow Results',
                'ordering': ['-started_at'],
            },
        ),
    ]
