# Generated by Django 5.0.14 on 2025-11-30 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Like'), ('view', 'View'), ('spinoff', 'Spin-off')], help_text='Type of interaction', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(help_text='Asset being interacted with', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='assets.ipasset')),
                ('user', models.ForeignKey(help_text='User who performed the interaction', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'asset', 'type')},
            },
        ),
    ]
