# Generated by Django 5.1.14 on 2025-12-05 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID for API access",
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Comment content", max_length=2000),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when comment was deleted",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset this comment is on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="assets.ipasset",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment if this is a reply",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="social.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who wrote the comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["asset", "-created_at"],
                        name="social_comm_asset_i_495549_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="social_comm_user_id_432175_idx",
                    ),
                    models.Index(
                        fields=["parent", "-created_at"],
                        name="social_comm_parent__4df9cb_idx",
                    ),
                    models.Index(
                        fields=["is_deleted", "-created_at"],
                        name="social_comm_is_dele_61eb3d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public UUID for API access",
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("view", "View"),
                            ("spinoff", "Spin-off"),
                        ],
                        help_text="Type of interaction",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset being interacted with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="assets.ipasset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the interaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction",
                "verbose_name_plural": "Interactions",
                "ordering": ["-created_at"],
                "unique_together": {("user", "asset", "type")},
            },
        ),
    ]
