# Generated by manual intervention

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion


def create_commentlike_if_not_exists(apps, schema_editor):
    """Create CommentLike table only if it doesn't already exist."""
    db_table = 'social_commentlike'
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name=?
        """, [db_table])
        table_exists = cursor.fetchone() is not None
        
        if not table_exists:
            # Create the table - this matches Django's SQLite output
            # Get the User model table name
            User = apps.get_model('auth', 'User')
            user_table = User._meta.db_table
            
            cursor.execute(f"""
                CREATE TABLE "{db_table}" (
                    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    "created_at" datetime NOT NULL,
                    "comment_id" bigint NOT NULL REFERENCES "social_comment" ("id") DEFERRABLE INITIALLY DEFERRED,
                    "user_id" integer NOT NULL REFERENCES "{user_table}" ("id") DEFERRABLE INITIALLY DEFERRED
                )
            """)
            # Create unique constraint
            cursor.execute(f"""
                CREATE UNIQUE INDEX "{db_table}_comment_id_user_id_uniq" 
                ON "{db_table}" ("comment_id", "user_id")
            """)
            # Create indexes for foreign keys
            cursor.execute(f"""
                CREATE INDEX "{db_table}_comment_id" 
                ON "{db_table}" ("comment_id")
            """)
            cursor.execute(f"""
                CREATE INDEX "{db_table}_user_id" 
                ON "{db_table}" ("user_id")
            """)


def reverse_create_commentlike(apps, schema_editor):
    """Reverse migration - drop the table if it exists."""
    db_table = 'social_commentlike'
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name=?
        """, [db_table])
        table_exists = cursor.fetchone() is not None
        
        if table_exists:
            cursor.execute(f'DROP TABLE "{db_table}"')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_commentlike_if_not_exists,
                    reverse_create_commentlike,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CommentLike',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('comment', models.ForeignKey(help_text='Comment being liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.comment')),
                        ('user', models.ForeignKey(help_text='User who liked the comment', on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Comment Like',
                        'verbose_name_plural': 'Comment Likes',
                        'unique_together': {('comment', 'user')},
                    },
                ),
            ],
        ),
    ]
